fix: synchronize databse with backend
SamuelBehrmann/mobile_anwendungen pull request #25
Opened 2024-06-25 20:47 UTC by SamuelBehrmann

2024-07-03 09:09 UTC, aminger-jan approved these changes

2024-07-03 09:12 UTC, luis-stumpf submitted a review, later dismissed
praise: super nice

2024-07-03 14:07 UTC, luis-stumpf requested changes
pls check the search again its deleting chars when typing

2024-07-04 06:29 UTC, SamuelBehrmann commented
> pls check the search again its deleting chars when typing

Unable to reproduce.

2024-07-04 07:58 UTC, luis-stumpf approved these changes

2024-07-04 09:27 UTC, merged